name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - name: Check format
        run: test -z $(gofmt -s -l .)

      - name: Lint
        uses: golangci/golangci-lint-action@v3

      - name: Build
        run: make metering
